"""Shared pytest fixtures for the GRACE test suite.

The organizer-provided competition data lives under ``downloaded_data/`` and is
NON-REDISTRIBUTABLE, so it is never present in CI. Tests that need realistic
inputs use the small, schema-correct synthetic fixtures committed under
``tests/fixtures/`` (generated by ``tests/_gen_fixtures.py``). Tests that
genuinely require the organizer artifacts skip cleanly when they are absent via
:data:`HAS_ORGANIZER_DATA`.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from grace.io.loaders import load_track1, load_track2

if TYPE_CHECKING:
    from grace.io.schema import GraceCase

FIXTURES = Path(__file__).parent / "fixtures"
TRACK1_FIXTURE = FIXTURES / "track1_sample.json"
TRACK2_FIXTURE = FIXTURES / "track2_sample.json"
FAKE_SCORER = FIXTURES / "fake_scorer.py"

# Organizer-provided, non-redistributable data (only present on a maintainer box).
_ORGANIZER_ROOT = Path("downloaded_data") / "public_data" / "public_data"
HAS_ORGANIZER_DATA = (_ORGANIZER_ROOT / "track_1_dev.json").exists()


@pytest.fixture
def track1_cases() -> tuple[GraceCase, ...]:
    return load_track1(TRACK1_FIXTURE)


@pytest.fixture
def track2_cases() -> tuple[GraceCase, ...]:
    return load_track2(TRACK2_FIXTURE)


@pytest.fixture
def fake_scorer_paths(monkeypatch: pytest.MonkeyPatch) -> Path:
    """Point ``grace.eval.scorer`` at the in-repo fake scorer for both tracks."""
    from grace.eval import scorer

    monkeypatch.setitem(scorer._SCORER_PATHS, 1, FAKE_SCORER)
    monkeypatch.setitem(scorer._SCORER_PATHS, 2, FAKE_SCORER)
    return FAKE_SCORER
